// Topology references (geometry and Russian names are original):
// https://jovianarchive.com/pages/get-your-human-design-chart
// https://jovianarchive.com/pages/human-design-dictionary
// https://jovianarchive.com/pages/channels-in-human-design-the-life-force
// Human Design is an interpretive system; these labels are not medical claims.

import { CENTERS as CENTER_IDS, GATES as GATE_IDS, CHANNELS as CHANNEL_IDS, canonicalChannelId } from '../domain/topology.js';

const centerNames = {
  head: "Теменной",
  ajna: "Аджна",
  throat: "Горловой",
  g: "G-центр",
  heart: "Эго",
  spleen: "Селезёночный",
  solar: "Солнечное сплетение",
  sacral: "Сакральный",
  root: "Корневой",
};
const gateNames = [
  "Творчество",
  "Направление",
  "Упорядочивание",
  "Ответы",
  "Ритмы",
  "Границы",
  "Роль в группе",
  "Вклад",
  "Фокус",
  "Поведение",
  "Идеи",
  "Осторожность",
  "Слушание",
  "Ресурсы",
  "Разнообразие",
  "Навыки",
  "Мнения",
  "Корректировка",
  "Потребности",
  "Настоящее",
  "Управление",
  "Открытость",
  "Объяснение",
  "Возвращение",
  "Невинность",
  "Убеждение",
  "Забота",
  "Смысл",
  "Обязательство",
  "Желания",
  "Влияние",
  "Непрерывность",
  "Уединение",
  "Сила",
  "Перемены",
  "Новый опыт",
  "Дружба",
  "Борьба",
  "Провокация",
  "Самостоятельность",
  "Воображение",
  "Завершение",
  "Озарение",
  "Распознавание",
  "Собирание",
  "Воплощённый опыт",
  "Осмысление",
  "Глубина",
  "Принципы",
  "Ценности",
  "Инициация",
  "Покой",
  "Начало",
  "Амбиция",
  "Дух",
  "Истории",
  "Интуитивная ясность",
  "Жизненность",
  "Близость",
  "Ограничения",
  "Внутренняя истина",
  "Детали",
  "Сомнение",
  "Образы",
];
const channelNames = {
  "47-64": "Абстракция",
  "24-61": "Осознанность",
  "4-63": "Логика",
  "17-62": "Принятие",
  "23-43": "Структурирование",
  "11-56": "Любознательность",
  "16-48": "Талант",
  "20-57": "Мозговая волна",
  "20-34": "Харизма",
  "10-20": "Пробуждение",
  "7-31": "Альфа",
  "1-8": "Вдохновение",
  "13-33": "Блудный сын",
  "35-36": "Мимолётность",
  "12-22": "Открытость",
  "21-45": "Деньги",
  "10-57": "Совершенная форма",
  "10-34": "Исследование",
  "34-57": "Сила",
  "25-51": "Инициация",
  "2-14": "Биение",
  "5-15": "Ритм",
  "29-46": "Открытие",
  "26-44": "Сдача",
  "37-40": "Сообщество",
  "27-50": "Сохранение",
  "6-59": "Близость",
  "9-52": "Концентрация",
  "3-60": "Мутация",
  "42-53": "Созревание",
  "18-58": "Суждение",
  "28-38": "Борьба",
  "32-54": "Трансформация",
  "19-49": "Синтез",
  "39-55": "Эмоциональность",
  "30-41": "Признание",
};

export const CENTERS = CENTER_IDS.map(center => ({ ...center, name: centerNames[center.id] }));
export const GATES = GATE_IDS.map(gate => ({ ...gate, name: gateNames[gate.id - 1] }));
export const CHANNELS = CHANNEL_IDS.map(channel => ({ ...channel, name: channelNames[channel.id] }));
const gatesById = new Map(GATES.map(gate => [gate.id, gate]));
const centersById = new Map(CENTERS.map(center => [center.id, center]));
const channelsById = new Map(CHANNELS.map(channel => [channel.id, channel]));
export const getGate = id => gatesById.get(Number(id));
export const getCenter = id => centersById.get(id);
export const getChannel = id => channelsById.get(canonicalChannelId(id));
