import fs from 'node:fs/promises';
import path from 'node:path';

// Every browser entry/dependency is explicit. Project files outside this map
// remain private even when a new directory or file is added to the repository.
export const PUBLIC_FILES = new Map([
  ['index.html', 'public/index.html'],
  ['styles.css', 'public/styles.css'],
  ['favicon.svg', 'public/favicon.svg'],
  ['love.html', 'public/love.html'],
  ['love', 'public/love.html'],
  ['love.css', 'public/love.css'],
  ...[
    'shared/day-packets/decode.js',
    'shared/day-packets/float64-codec.js',
    'shared/day-packets/natal-format.js',
    'shared/day-packets/transit-format.js',
    'src/app.js',
    'src/data/api-client.js',
    'src/data/chart-store.js',
    'src/data/natal-day-cache.js',
    'src/data/natal-day-client.js',
    'src/data/storage.js',
    'src/data/transit-day-client.js',
    'src/domain/chart-facts.js',
    'src/domain/day-timeline.js',
    'src/domain/gate-wheel.js',
    'src/domain/line-fixing-data.js',
    'src/domain/line-fixing.js',
    'src/domain/mandala-cross.js',
    'src/domain/natal-day.js',
    'src/domain/planets.js',
    'src/domain/substructure.js',
    'src/domain/topology.js',
    'src/domain/transit-day.js',
    'src/domain/variables.js',
    'src/reference/catalog.js',
    'src/scene/activation-columns.js',
    'src/scene/activation-painter.js',
    'src/scene/backdrop.js',
    'src/scene/bodygraph-paint.js',
    'src/scene/bodygraph-painter.js',
    'src/scene/bodygraph-svg.js',
    'src/scene/camera.js',
    'src/scene/geometry/activation-layout.js',
    'src/scene/geometry/chart-backdrop.js',
    'src/scene/geometry/chart-geometry.js',
    'src/scene/geometry/drawing-geometry.js',
    'src/scene/geometry/frames.js',
    'src/scene/geometry/integration-geometry.js',
    'src/scene/geometry/lotus-backdrop.js',
    'src/scene/geometry/mandala-geometry.js',
    'src/scene/gestures.js',
    'src/scene/layout.js',
    'src/scene/mandala-painter.js',
    'src/scene/mandala-preview-painter.js',
    'src/scene/mandala-preview.js',
    'src/scene/mandala-underlay.js',
    'src/scene/mandala.js',
    'src/scene/modes/lotus.js',
    'src/scene/modes/mandala-motion.js',
    'src/scene/modes/mandala.js',
    'src/scene/render-state.js',
    'src/scene/renderer.js',
    'src/scene/studio-controller.js',
    'src/scene/svg-patches.js',
    'src/scene/updates.js',
    'src/scene/variable-arrows.js',
    'src/selection/hover-preview.js',
    'src/selection/mandala-selection-state.js',
    'src/selection/selection-model.js',
    'src/selection/selection-state.js',
    'src/selection/selection-targets.js',
    'src/selection/summary-selection-state.js',
    'src/state/chart-session.js',
    'src/state/live-transit.js',
    'src/state/natal-day.js',
    'src/stories/vessel-of-love.js',
    'src/ui/html.js',
    'src/ui/telegram-gestures.js',
    'src/ui/toast.js',
    'src/views/activation-details.js',
    'src/views/activation-popover.js',
    'src/views/birth-form.js',
    'src/views/camera-controls.js',
    'src/views/chart-display.js',
    'src/views/chart-heading-layout.js',
    'src/views/chart-summary-data.js',
    'src/views/chart-summary-panel.js',
    'src/views/date-input.js',
    'src/views/day-range.js',
    'src/views/knowledge.js',
    'src/views/library.js',
    'src/views/live-transit.js',
    'src/views/natal-day-controls.js',
    'src/views/thumbnail.js',
    'src/views/transit-controls.js',
  ].map(filename => [filename, filename]),
]);
const CONTENT_TYPES = { '.html': 'text/html; charset=utf-8', '.js': 'text/javascript; charset=utf-8', '.css': 'text/css; charset=utf-8', '.svg': 'image/svg+xml', '.json': 'application/json; charset=utf-8' };

export async function servePublicFile(root, req, res, pathname) {
  if (req.method !== 'GET' && req.method !== 'HEAD') { res.writeHead(405, { Allow: 'GET, HEAD' }); res.end(); return; }
  const filename = pathname === '/' ? 'index.html' : decodeURIComponent(pathname.slice(1));
  const file = PUBLIC_FILES.get(filename);
  if (!file) { res.writeHead(404); res.end('Not found'); return; }
  const data = await fs.readFile(path.join(root, file));
  res.writeHead(200, { 'Content-Type': CONTENT_TYPES[path.extname(file)] || 'text/plain', 'Cache-Control': 'no-cache', 'X-Content-Type-Options': 'nosniff' });
  res.end(req.method === 'HEAD' ? undefined : data);
}
